
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/proj-courses-s23-7pm-1
owner: ucsb-cs156-s23
repo_name: proj-courses-s23-7pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjYwMTI0ODcz","is_bot":false,"login":"b4k3s","name":""},"headRefName":"Christian-AddMongoDBCollections","number":42,"title":"Add Update.java and UpdateCollection.java","url":"https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-1/pull/42"},{"author":{"id":"U_kgDOB0-WaA","is_bot":false,"login":"BenCrutt","name":""},"headRefName":"Ben-instructorSearchPage","number":36,"title":"Ben instructor search page","url":"https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-1/pull/36"},{"author":{"id":"MDQ6VXNlcjQ5NjY0Njg5","is_bot":false,"login":"kdhulipala41","name":"Krishna Dhulipala"},"headRefName":"Krishna-selectAllQuartersInDropdown","number":34,"title":"KD - added frontend 'select all' button in quarters dropdown","url":"https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-1/pull/34"}]
