
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/proj-courses-s23-7pm-1
owner: ucsb-cs156-s23
repo_name: proj-courses-s23-7pm-1
pull_requests: [{"author":{"id":"U_kgDOB0-WaA","is_bot":false,"login":"BenCrutt","name":""},"headRefName":"Ben-instructorSearchPage","number":36,"title":"Ben instructor search page","url":"https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-1/pull/36"},{"author":{"id":"MDQ6VXNlcjc3NTIxMjQ5","is_bot":false,"login":"cameron-barrett","name":"Cameron Barrett"},"headRefName":"Cameron-CreateFixturesDocumentToTrackSubjectChanges","number":35,"title":"Cameron create fixtures document to track subject changes","url":"https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-1/pull/35"},{"author":{"id":"MDQ6VXNlcjQ5NjY0Njg5","is_bot":false,"login":"kdhulipala41","name":"Krishna Dhulipala"},"headRefName":"Krishna-selectAllQuartersInDropdown","number":34,"title":"KD - added frontend 'select all' button in quarters dropdown","url":"https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-1/pull/34"},{"author":{"id":"MDQ6VXNlcjQyMzY2OTc2","is_bot":false,"login":"asojonih08","name":""},"headRefName":"Ricardo-courseGradeHistoryEntityRepository","number":31,"title":"rh - added Grade History Entity and Repository","url":"https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-1/pull/31"},{"author":{"id":"MDQ6VXNlcjc3NTIxMjQ5","is_bot":false,"login":"cameron-barrett","name":"Cameron Barrett"},"headRefName":"Cameron-ChangeThemeToBlue","number":30,"title":"Cameron change theme to blue","url":"https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-1/pull/30"},{"author":{"id":"U_kgDOB0-WaA","is_bot":false,"login":"BenCrutt","name":""},"headRefName":"Ben-instructorMenuOption","number":29,"title":"bc - added menu option for search by instructor","url":"https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-1/pull/29"}]
