
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/proj-courses-s23-7pm-1
owner: ucsb-cs156-s23
repo_name: proj-courses-s23-7pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjc3NTIxMjQ5","is_bot":false,"login":"cameron-barrett","name":"Cameron Barrett"},"headRefName":"Cameron-ChangeThemeToBlue","number":30,"title":"Cameron change theme to blue","url":"https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-1/pull/30"},{"author":{"id":"U_kgDOB0-WaA","is_bot":false,"login":"BenCrutt","name":""},"headRefName":"Ben-instructorMenuOption","number":29,"title":"bc - added menu option for search by instructor","url":"https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-1/pull/29"},{"author":{"id":"MDQ6VXNlcjYwMTI0ODcz","is_bot":false,"login":"b4k3s","name":""},"headRefName":"Christian-UpdateREADME","number":8,"title":"Update README urls to reflect our project","url":"https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-1/pull/8"}]
